[project]
name = "kruase-telegram-bot"
version = "1.0.0"
description = "My first multi-purpose Telegram bot"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiogram>=3.17.0",
    "pyyaml>=6.0.2",
]
